// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Data;

#nullable disable

namespace TodoApi.Migrations
{
  [DbContext(typeof(TodoDbContext))]
  [Migration("20260407182656_InitialCreate")]
  partial class InitialCreate
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

      modelBuilder.Entity("todo_api.Models.TodoItem", b =>
      {
        b.Property<int>("Id")
          .ValueGeneratedOnAdd()
          .HasColumnType("INTEGER");

        b.Property<DateTimeOffset>("CreatedAt")
          .HasColumnType("TEXT");

        b.Property<DateTimeOffset?>("DeletedAt")
          .HasColumnType("TEXT");

        b.Property<bool>("IsCompleted")
          .HasColumnType("INTEGER");

        b.Property<string>("Title")
          .IsRequired()
          .HasMaxLength(200)
          .HasColumnType("TEXT");

        b.Property<DateTimeOffset>("UpdatedAt")
          .HasColumnType("TEXT");

        b.HasKey("Id");

        b.ToTable("Todos");
      });
#pragma warning restore 612, 618
    }
  }
}
